### ISSUE TITLE
System.NotImplementedException

### ISSUE THREAD

**Issue by prestonwindfeldt** [ezhevita/SteamKitProxyInjection#399]
I am trying to figure out how to use this plugin so that I can proxy communications with Steam while using ASF. I am on a Mac ARM64 architecture.

**dotnet version and runtimes:**
8.0.402
Microsoft.AspNetCore.App 8.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Error logs trying to use SteamKitProxyInjection latest with ASF Generic 6.0.8.7**

2024-11-05 15:22:53|dotnet-3089|INFO|ASF|OnASFInit() Injecting...
2024-11-05 15:22:53|dotnet-3089|TRACE|ASF|OnASFInit() Retrieving WebSocketConnection and WebSocketContext types...
2024-11-05 15:22:53|dotnet-3089|TRACE|ASF|OnASFInit() Retrieving WebSocketContext constructor...
2024-11-05 15:22:53|dotnet-3089|TRACE|ASF|OnASFInit() Patching...
2024-11-05 15:22:53|dotnet-3089|ERROR|ASF|OnASFInitModules() System.NotImplementedException: The method or operation is not implemented.
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   at SteamKitProxyInjection.SteamKitProxyInjectionPlugin.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)
   at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass14_0.<OnASFInitModules>b__0(IASF plugin)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnASFInitModules(IReadOnlyDictionary`2 additionalConfigProperties)

**Comment by prestonwindfeldt** [comment]
This issue went away after trying to run everything on a Windows machine instead of a Mac.
