### ISSUE TITLE
CoreCLR is nort supported

### ISSUE THREAD

**Issue by Medicxx2** [ezhevita/SteamKitProxyInjection#406]
I have problem run this plugin.
Error in ASF-win-x64 is 

> 2024-12-13 12:25:38|ArchiSteamFarm-12036|INFO|ASF|InitCore() ArchiSteamFarm V6.1.0.3 (win-x64/e69b2960467e4fa08cd8f1c77fa67a01 | .NET 9.0.0; win-x64; Microsoft Windows 10.0.19045) in [C:\Users\]
> 2024-12-13 12:25:38|ArchiSteamFarm-12036|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
> 2024-12-13 12:25:38|ArchiSteamFarm-12036|INFO|ASF|InitPlugins() Initializing Plugins...
> 2024-12-13 12:25:38|ArchiSteamFarm-12036|ERROR|ASF|InitPlugins() Failed due to error: 0Harmony, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null
> 2024-12-13 12:25:38|ArchiSteamFarm-12036|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
> 
>    at System.Reflection.RuntimeModule.GetTypes(QCallModule, ObjectHandleOnStack)
>    at System.Reflection.RuntimeModule.GetDefinedTypes()
>    at System.Reflection.RuntimeModule.GetTypes()
>    at System.Reflection.Assembly.GetTypes()
>    at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> System.TypeLoadException
> 2024-12-13 12:25:48|ArchiSteamFarm-12036|ERROR|ASF|Exit() Exiting with 1 error code!

in  ASF-generic version is

> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitCore() ArchiSteamFarm V6.1.0.3 (generic/2386970dbc17433a818fd5b39afe35a3 | .NET 9.0.0; win-x64; Microsoft Windows 10.0.19045) in [C:\Users\]
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitCore() Copyright © 2015-2024 JustArchiNET
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitPlugins() Initializing Plugins...
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitPlugins() Loading ItemsMatcherPlugin V6.1.0.3...
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitPlugins() ItemsMatcherPlugin has been loaded successfully!
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitPlugins() Loading MobileAuthenticatorPlugin V6.1.0.3...
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitPlugins() MobileAuthenticatorPlugin has been loaded successfully!
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitPlugins() Loading SteamTokenDumperPlugin V6.1.0.3...
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitPlugins() SteamTokenDumperPlugin has been loaded successfully!
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitPlugins() Loading SteamKitProxyInjection V2.3.0.0...
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|OnLoaded() SteamKitProxyInjection by ezhevita | Support & source code: https://github.com/ezhevita/SteamKitProxyInjection
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitPlugins() SteamKitProxyInjection has been loaded successfully!
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|InitPlugins() You've loaded one or multiple custom plugins into ASF. Since we're unable to offer support for modded setups, please contact the appropriate developers of the plugins that you decided to use in case of any issues.
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|Load() Loading STD global cache...
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|OnASFInit() Injecting...
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|Load() Validating STD global cache integrity...
> 2024-12-13 12:31:18|dotnet-15104|INFO|ASF|OnASFInit() SteamTokenDumperPlugin is currently disabled according to your configuration. If you'd like to help SteamDB in data submission, please check out our wiki.
> 2024-12-13 12:31:19|dotnet-15104|ERROR|ASF|OnASFInitModules() System.PlatformNotSupportedException: CoreCLR version 9.0.0 is not supported
>    at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
>    at HarmonyLib.PatchProcessor.Patch()
>    at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
>    at SteamKitProxyInjection.SteamKitProxyInjectionPlugin.OnASFInit(IReadOnlyDictionary`2 additionalConfigProperties)
>    at ArchiSteamFarm.Plugins.PluginsCore.<>c__DisplayClass14_0.<OnASFInitModules>b__0(IASF plugin)
>    at System.Linq.Enumerable.IEnumerableWhereSelectIterator`2.MoveNext()
>    at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
>    at ArchiSteamFarm.Core.Utilities.InParallel(IEnumerable`1 tasks)
>    at ArchiSteamFarm.Plugins.PluginsCore.OnASFInitModules(IReadOnlyDictionary`2 additionalConfigProperties)
> 2024-12-13 12:31:19|dotnet-15104|INFO|ASF|StartInteractiveConsole() Interactive console is now active, type 'c' in order to enter command mode.
> 2024-12-13 12:31:19|dotnet-15104|INFO|ASF|Start() Starting IPC server...
> 2024-12-13 12:31:19|dotnet-15104|INFO|Microsoft.Hosting.Lifetime|Now listening on: http://[::]:10000
> 2024-12-13 12:31:19|dotnet-15104|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
> 2024-12-13 12:31:19|dotnet-15104|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Production
> 2024-12-13 12:31:19|dotnet-15104|INFO|Microsoft.Hosting.Lifetime|Content root path: C:\Users\
> 2024-12-13 12:31:19|dotnet-15104|INFO|ASF|Start() IPC server ready!

**Comment by ezhevita** [comment]
Hi, thanks for the report!
Plugin doesn't support any other version except generic due to the trimming.
And the crash on generic version occurs due to the Harmony, a library that does all the runtime patching, not supporting the .NET 9 runtime, you can track the issue here: https://github.com/pardeike/Harmony/issues/635
I may consider switching to the custom-built version if it works out of the box, but this is an issue for later

**Comment by ezhevita** [comment]
@Medicxx2 it should be fixed in the 2.4.0 release, can you test it please?
